ports:
  dns: 53
  http: 4000

bootstrapDns:
  - upstream: tcp+udp:1.1.1.1

upstreams:
  groups:
    # these external DNS resolvers will be used. Blocky picks 2 random resolvers from the list for each query
    default:
      # Cloudflare
      - tcp-tls:1.1.1.1:853
      - tcp-tls:1.0.0.1:853

# configuration of client name resolution
clientLookup:
  upstream: 10.5.0.3

ecs:
  useAsClient: true
  forward: true

ede:
  enable: true

prometheus:
  enable: true
  path: /metrics

caching:
  minTime: 5m
  maxTime: 30m
  prefetching: true

blocking:
  loading:
    downloads:
      timeout: 4m

  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    fakenews:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-only/hosts
    gambling:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-only/hosts

  clientGroupsBlock:
    default:
      - ads
      - fakenews
      - gambling
